[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
axum = "0.7.7"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sqlx = { version = "0.8.2", features = [
    "postgres",
    "runtime-tokio",
    "migrate",
    "uuid",
    "time",
    "chrono",
    "bigdecimal",
] }
bigdecimal = "0.3.1"
tokio = { version = "1.40.0", features = ["full"] }
tower-http = { version = "0.6.1", features = ["cors"] }
relayer-utils = { git = "https://github.com/zkemail/relayer-utils.git", branch = "main" }
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_warn",
] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }
chrono = { version = "0.4.38", features = ["serde"] }
ethers = "2.0.14"
reqwest = { version = "0.12.8", features = ["json"] }
handlebars = "6.1.0"
regex = "1.11.0"
ic-agent = { version = "0.37.1", features = ["pem", "reqwest"] }
ic-utils = "0.37.0"
candid = "0.10.10"
lazy_static = "1.5.0"

[build-dependencies]
ethers = "2.0.14"
